import { Asset, getConfigOption, sanitize, SharedLink } from '@ipp/core'
import { createHash } from 'crypto'
import { ImageSize } from '../types'
import { resolveImageEndpoint } from './sizing'

/**
 * Where an asset sits in its share, for the position-based download names of
 * `downloadedFilename: 2`. Built with `positionInShare` / `findPositionInShare`.
 */
export interface AssetPosition {
  /** The share's key. Only its hash reaches a filename, never the key itself. */
  shareKey: string
  /** 1-based index of the asset in the share's display order */
  position: number
  /** Number of assets in the share, which sets the zero-padding width */
  count: number
}

/**
 * The position of the asset at `index` in `share.assets`, which is already in
 * display order (see gallery/order.ts).
 */
export function positionInShare (share: SharedLink, index: number): AssetPosition {
  return { shareKey: share.key, position: index + 1, count: share.assets.length }
}

/**
 * Look up an asset's position in its share by id. A motion photo's clip takes
 * the position of the still it belongs to. Undefined when the id is not in
 * the share, which `getFilename` treats as "no position".
 */
export function findPositionInShare (share: SharedLink, assetId: string): AssetPosition | undefined {
  const index = share.assets.findIndex(a => a.id === assetId || a.livePhotoVideoId === assetId)
  return index === -1 ? undefined : positionInShare(share, index)
}

/** `ipp.downloadedFilename` when the operator's config omits it: share hash plus position */
const DEFAULT_FILENAME_MODE = 2

/** Shortest zero-padding for a position: the digits in the asset count, minimum 3 */
const MIN_POSITION_DIGITS = 3

/**
 * Filename stem for `downloadedFilename: 2`: the first 8 hex characters of
 * SHA-256 of the share key, an underscore, then the zero-padded position,
 * e.g. `a3f9c2e1_001`. Hashing the key keeps the share's secret out of the
 * name; it is the key, not the slug, so a share reached either way gets the
 * same names.
 */
export function positionStem ({ shareKey, position, count }: AssetPosition): string {
  const prefix = createHash('sha256').update(shareKey).digest('hex').slice(0, 8)
  const digits = Math.max(MIN_POSITION_DIGITS, String(count).length)
  return prefix + '_' + String(position).padStart(digits, '0')
}

/**
 * Map a MIME type to a file extension (including the dot), case-insensitively.
 * Returns '' for unknown types; obscure RAW types fall through to '' so
 * the original filename (which usually has the correct extension) is
 * preserved by `withMimeExtension`.
 */
function mimeToExt (mime: string | undefined): string {
  if (!mime) return ''
  const map: Record<string, string> = {
    'image/jpeg': '.jpg',
    'image/png': '.png',
    'image/webp': '.webp',
    'image/gif': '.gif',
    'image/heic': '.heic',
    'image/heif': '.heif',
    'image/avif': '.avif',
    'image/tiff': '.tiff',
    'image/svg+xml': '.svg',
    'image/x-adobe-dng': '.dng',
    'video/mp4': '.mp4',
    'video/quicktime': '.mov',
    'video/webm': '.webm',
    'video/x-msvideo': '.avi',
    'video/x-matroska': '.mkv'
  }
  return map[mime.toLowerCase()] || ''
}

/**
 * Append the MIME-derived extension to `filename` if it isn't already
 * present (case-insensitive). Returns the filename unchanged when the
 * MIME isn't in our map. Aliases that share a MIME type (`.jpg`/`.jpeg`,
 * `.tif`/`.tiff`) are accepted as already-present so we don't produce
 * `IMG.jpeg.jpg` for an `image/jpeg` asset.
 */
function withMimeExtension (filename: string, mime: string | undefined): string {
  const ext = mimeToExt(mime)
  if (!ext) return filename
  const aliases: Record<string, string[]> = {
    '.jpg': ['.jpg', '.jpeg'],
    '.tiff': ['.tif', '.tiff']
  }
  const acceptable = aliases[ext] ?? [ext]
  const lower = filename.toLowerCase()
  return acceptable.some(a => lower.endsWith(a)) ? filename : filename + ext
}

/**
 * Generate a filename for the downloaded asset based on the configuration option chosen.
 *
 * The extension follows the served bytes, not the original.
 *
 * @param asset
 * @param [servedSize] - what size Immich will actually serve. Defaults to
 *   ImageSize.original (the bytes match the original asset).
 * @param [servedMimeOverride] - MIME of Immich-generated bytes (see servedMimeFrom).
 *   Ignored if unmapped, so it can't strip the extension.
 * @param [position] - the asset's place in its share, which `downloadedFilename: 2`
 *   names by. Without it that mode falls back to the asset ID.
 */
export function getFilename (asset: Asset, servedSize: ImageSize = ImageSize.original, servedMimeOverride?: string, position?: AssetPosition): string {
  const override = mimeToExt(servedMimeOverride) ? servedMimeOverride : undefined
  let servedMime: string | undefined
  if (override) {
    servedMime = override
  } else if (servedSize === ImageSize.original) {
    servedMime = asset.originalMimeType
  } else if (servedSize === ImageSize.thumbnail) {
    servedMime = 'image/webp'
  } else {
    servedMime = 'image/jpeg'
  }

  switch (getConfigOption('ipp.downloadedFilename', DEFAULT_FILENAME_MODE)) {
    case 1:
      // Immich's ID number for this asset
      return withMimeExtension(asset.id, servedMime)
    case 2:
      // Anonymous and deterministic: share-hash prefix plus album position,
      // so a re-download of the same share overwrites the first copy.
      return withMimeExtension(position ? positionStem(position) : asset.id, servedMime)
    default: {
      // By default, use the asset's original filename
      const cleanName = asset.originalFileName ? sanitize(asset.originalFileName) : ''
      if (!cleanName) return withMimeExtension(asset.id, servedMime)
      // Keep the original extension only when the served bytes really are the
      // original file; a size downgrade or playback transcode replaces it.
      const stem = servedSize === ImageSize.original && !override
        ? cleanName
        : cleanName.replace(/\.[a-zA-Z0-9]{2,5}$/, '')
      return withMimeExtension(stem, servedMime)
    }
  }
}

/**
 * Filename for a download link's `download` attribute. Converted tiers are assumed
 * JPEG; the download's Content-Disposition, which browsers prefer, has the real name.
 */
export function downloadFilename (asset: Asset, position?: AssetPosition): string {
  return getFilename(asset, resolveImageEndpoint(ImageSize.original, asset).servedSize, undefined, position)
}

/** Download Content-Disposition, RFC 5987-encoded so `,` and `;` can't split the header. */
export function attachmentDisposition (filename: string): string {
  const encoded = encodeURIComponent(filename)
    .replace(/['()*]/g, c => '%' + c.charCodeAt(0).toString(16).toUpperCase())
  return `attachment; filename*=UTF-8''${encoded}`
}

/** Content-type without its parameters, or undefined if absent. */
export function responseMime (response: globalThis.Response): string | undefined {
  return (response.headers.get('content-type') || '').split(';')[0].trim() || undefined
}

/** Content-type of Immich-generated bytes (anything but /original), to name the file by. */
export function servedMimeFrom (subpath: string, response: globalThis.Response): string | undefined {
  return subpath === '/original' ? undefined : responseMime(response)
}

/**
 * Fill in originalFileName / originalMimeType from an asset response's
 * `Content-Disposition` / `Content-Type` headers, for assets that arrived
 * without them (lazy album grid assets). Returns a shallow copy so the cached
 * share asset is never mutated.
 */
export function enrichFromHeaders (asset: Asset, response: globalThis.Response): Asset {
  const fileName = filenameFromContentDisposition(response.headers.get('content-disposition'))
  const mime = responseMime(response)
  if (!fileName && !mime) return asset
  return {
    ...asset,
    originalFileName: asset.originalFileName || fileName,
    originalMimeType: asset.originalMimeType || mime
  }
}

/**
 * Extract a filename from a `Content-Disposition` header. Prefers the RFC 5987
 * `filename*=UTF-8''...` form (percent-decoded) over the plain `filename=`.
 * Returns undefined when neither is present.
 */
export function filenameFromContentDisposition (header: string | null): string | undefined {
  if (!header) return undefined
  const extended = header.match(/filename\*=(?:UTF-8'')?([^;]+)/i)
  if (extended) {
    const raw = extended[1].trim().replace(/^"|"$/g, '')
    try {
      return decodeURIComponent(raw)
    } catch (e) {
      return raw
    }
  }
  const plain = header.match(/filename="?([^";]+)"?/i)
  return plain ? plain[1].trim() : undefined
}
